name: lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install libraries (Linux)
        # install libheif (and dependency libde265) from the PPA which is more
        # current; Ubuntu's is too old, resulting in failed compilation
        run: |
          sudo add-apt-repository ppa:strukturag/libheif
          sudo add-apt-repository ppa:strukturag/libde265
          sudo apt-get update
          sudo apt-get install -y libheif-dev libvips-dev
          sudo ldconfig

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: downgrade heif
        run: |
          go get github.com/strukturag/libheif@v1.17.6
          go mod tidy

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
